// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamerUploader.proto

package it.geosystems.csa.protocolbuffer;

public final class StreamerUploaderProtos {
  private StreamerUploaderProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AudioChunkUploaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:it.geosystems.csa.protocolbuffer.AudioChunkUploader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 offset = 1;</code>
     */
    boolean hasOffset();
    /**
     * <code>optional int64 offset = 1;</code>
     */
    long getOffset();

    /**
     * <code>optional bytes data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>optional string username = 3;</code>
     */
    boolean hasUsername();
    /**
     * <code>optional string username = 3;</code>
     */
    String getUsername();
    /**
     * <code>optional string username = 3;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>optional int64 datainvio = 4;</code>
     */
    boolean hasDatainvio();
    /**
     * <code>optional int64 datainvio = 4;</code>
     */
    long getDatainvio();

    /**
     * <code>optional string idperiferica = 5;</code>
     */
    boolean hasIdperiferica();
    /**
     * <code>optional string idperiferica = 5;</code>
     */
    String getIdperiferica();
    /**
     * <code>optional string idperiferica = 5;</code>
     */
    com.google.protobuf.ByteString
        getIdperifericaBytes();

    /**
     * <code>optional string password = 6;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 6;</code>
     */
    String getPassword();
    /**
     * <code>optional string password = 6;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code it.geosystems.csa.protocolbuffer.AudioChunkUploader}
   */
  public  static final class AudioChunkUploader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:it.geosystems.csa.protocolbuffer.AudioChunkUploader)
      AudioChunkUploaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AudioChunkUploader.newBuilder() to construct.
    private AudioChunkUploader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AudioChunkUploader() {
      offset_ = 0L;
      data_ = com.google.protobuf.ByteString.EMPTY;
      username_ = "";
      datainvio_ = 0L;
      idperiferica_ = "";
      password_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AudioChunkUploader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              offset_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              username_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              datainvio_ = input.readInt64();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              idperiferica_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              password_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.internal_static_it_geosystems_csa_protocolbuffer_AudioChunkUploader_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.internal_static_it_geosystems_csa_protocolbuffer_AudioChunkUploader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader.class, it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader.Builder.class);
    }

    private int bitField0_;
    public static final int OFFSET_FIELD_NUMBER = 1;
    private long offset_;
    /**
     * <code>optional int64 offset = 1;</code>
     */
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 offset = 1;</code>
     */
    public long getOffset() {
      return offset_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int USERNAME_FIELD_NUMBER = 3;
    private volatile Object username_;
    /**
     * <code>optional string username = 3;</code>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string username = 3;</code>
     */
    public String getUsername() {
      Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATAINVIO_FIELD_NUMBER = 4;
    private long datainvio_;
    /**
     * <code>optional int64 datainvio = 4;</code>
     */
    public boolean hasDatainvio() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 datainvio = 4;</code>
     */
    public long getDatainvio() {
      return datainvio_;
    }

    public static final int IDPERIFERICA_FIELD_NUMBER = 5;
    private volatile Object idperiferica_;
    /**
     * <code>optional string idperiferica = 5;</code>
     */
    public boolean hasIdperiferica() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string idperiferica = 5;</code>
     */
    public String getIdperiferica() {
      Object ref = idperiferica_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          idperiferica_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string idperiferica = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIdperifericaBytes() {
      Object ref = idperiferica_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        idperiferica_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 6;
    private volatile Object password_;
    /**
     * <code>optional string password = 6;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string password = 6;</code>
     */
    public String getPassword() {
      Object ref = password_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, offset_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, username_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, datainvio_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, idperiferica_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, password_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, offset_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, username_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, datainvio_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, idperiferica_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader)) {
        return super.equals(obj);
      }
      it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader other = (it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader) obj;

      boolean result = true;
      result = result && (hasOffset() == other.hasOffset());
      if (hasOffset()) {
        result = result && (getOffset()
            == other.getOffset());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && (hasUsername() == other.hasUsername());
      if (hasUsername()) {
        result = result && getUsername()
            .equals(other.getUsername());
      }
      result = result && (hasDatainvio() == other.hasDatainvio());
      if (hasDatainvio()) {
        result = result && (getDatainvio()
            == other.getDatainvio());
      }
      result = result && (hasIdperiferica() == other.hasIdperiferica());
      if (hasIdperiferica()) {
        result = result && getIdperiferica()
            .equals(other.getIdperiferica());
      }
      result = result && (hasPassword() == other.hasPassword());
      if (hasPassword()) {
        result = result && getPassword()
            .equals(other.getPassword());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOffset()) {
        hash = (37 * hash) + OFFSET_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getOffset());
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      if (hasUsername()) {
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUsername().hashCode();
      }
      if (hasDatainvio()) {
        hash = (37 * hash) + DATAINVIO_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getDatainvio());
      }
      if (hasIdperiferica()) {
        hash = (37 * hash) + IDPERIFERICA_FIELD_NUMBER;
        hash = (53 * hash) + getIdperiferica().hashCode();
      }
      if (hasPassword()) {
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code it.geosystems.csa.protocolbuffer.AudioChunkUploader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:it.geosystems.csa.protocolbuffer.AudioChunkUploader)
        it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.internal_static_it_geosystems_csa_protocolbuffer_AudioChunkUploader_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.internal_static_it_geosystems_csa_protocolbuffer_AudioChunkUploader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader.class, it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader.Builder.class);
      }

      // Construct using it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        offset_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        datainvio_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        idperiferica_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.internal_static_it_geosystems_csa_protocolbuffer_AudioChunkUploader_descriptor;
      }

      @Override
      public it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader getDefaultInstanceForType() {
        return it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader.getDefaultInstance();
      }

      @Override
      public it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader build() {
        it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader buildPartial() {
        it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader result = new it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.offset_ = offset_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.datainvio_ = datainvio_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.idperiferica_ = idperiferica_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader) {
          return mergeFrom((it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader other) {
        if (other == it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader.getDefaultInstance()) return this;
        if (other.hasOffset()) {
          setOffset(other.getOffset());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasUsername()) {
          bitField0_ |= 0x00000004;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasDatainvio()) {
          setDatainvio(other.getDatainvio());
        }
        if (other.hasIdperiferica()) {
          bitField0_ |= 0x00000010;
          idperiferica_ = other.idperiferica_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000020;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long offset_ ;
      /**
       * <code>optional int64 offset = 1;</code>
       */
      public boolean hasOffset() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 offset = 1;</code>
       */
      public long getOffset() {
        return offset_;
      }
      /**
       * <code>optional int64 offset = 1;</code>
       */
      public Builder setOffset(long value) {
        bitField0_ |= 0x00000001;
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 offset = 1;</code>
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000001);
        offset_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private Object username_ = "";
      /**
       * <code>optional string username = 3;</code>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string username = 3;</code>
       */
      public String getUsername() {
        Object ref = username_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string username = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 3;</code>
       */
      public Builder setUsername(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 3;</code>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000004);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 3;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        username_ = value;
        onChanged();
        return this;
      }

      private long datainvio_ ;
      /**
       * <code>optional int64 datainvio = 4;</code>
       */
      public boolean hasDatainvio() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 datainvio = 4;</code>
       */
      public long getDatainvio() {
        return datainvio_;
      }
      /**
       * <code>optional int64 datainvio = 4;</code>
       */
      public Builder setDatainvio(long value) {
        bitField0_ |= 0x00000008;
        datainvio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 datainvio = 4;</code>
       */
      public Builder clearDatainvio() {
        bitField0_ = (bitField0_ & ~0x00000008);
        datainvio_ = 0L;
        onChanged();
        return this;
      }

      private Object idperiferica_ = "";
      /**
       * <code>optional string idperiferica = 5;</code>
       */
      public boolean hasIdperiferica() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string idperiferica = 5;</code>
       */
      public String getIdperiferica() {
        Object ref = idperiferica_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            idperiferica_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string idperiferica = 5;</code>
       */
      public com.google.protobuf.ByteString
          getIdperifericaBytes() {
        Object ref = idperiferica_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          idperiferica_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string idperiferica = 5;</code>
       */
      public Builder setIdperiferica(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        idperiferica_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string idperiferica = 5;</code>
       */
      public Builder clearIdperiferica() {
        bitField0_ = (bitField0_ & ~0x00000010);
        idperiferica_ = getDefaultInstance().getIdperiferica();
        onChanged();
        return this;
      }
      /**
       * <code>optional string idperiferica = 5;</code>
       */
      public Builder setIdperifericaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        idperiferica_ = value;
        onChanged();
        return this;
      }

      private Object password_ = "";
      /**
       * <code>optional string password = 6;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string password = 6;</code>
       */
      public String getPassword() {
        Object ref = password_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string password = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 6;</code>
       */
      public Builder setPassword(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 6;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000020);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 6;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        password_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:it.geosystems.csa.protocolbuffer.AudioChunkUploader)
    }

    // @@protoc_insertion_point(class_scope:it.geosystems.csa.protocolbuffer.AudioChunkUploader)
    private static final it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader();
    }

    public static it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<AudioChunkUploader>
        PARSER = new com.google.protobuf.AbstractParser<AudioChunkUploader>() {
      @Override
      public AudioChunkUploader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AudioChunkUploader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AudioChunkUploader> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AudioChunkUploader> getParserForType() {
      return PARSER;
    }

    @Override
    public it.geosystems.csa.protocolbuffer.StreamerUploaderProtos.AudioChunkUploader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_it_geosystems_csa_protocolbuffer_AudioChunkUploader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_it_geosystems_csa_protocolbuffer_AudioChunkUploader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026StreamerUploader.proto\022 it.geosystems." +
      "csa.protocolbuffer\"\177\n\022AudioChunkUploader" +
      "\022\016\n\006offset\030\001 \001(\003\022\014\n\004data\030\002 \001(\014\022\020\n\010userna" +
      "me\030\003 \001(\t\022\021\n\tdatainvio\030\004 \001(\003\022\024\n\014idperifer" +
      "ica\030\005 \001(\t\022\020\n\010password\030\006 \001(\tB:\n it.geosys" +
      "tems.csa.protocolbufferB\026StreamerUploade" +
      "rProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_it_geosystems_csa_protocolbuffer_AudioChunkUploader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_it_geosystems_csa_protocolbuffer_AudioChunkUploader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_it_geosystems_csa_protocolbuffer_AudioChunkUploader_descriptor,
        new String[] { "Offset", "Data", "Username", "Datainvio", "Idperiferica", "Password", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
